config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login' => 'devise/sessions#create'
  end

  resources :users

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#Home'

  resources :blogs
  resources :courses, :path => :classes 
  resources :projects

  get 'news' => 'blogs#index'
  get 'blog' => 'blogs#indexBlog'
  get 'projects' => 'projects#index'
  get 'about' => 'users#index'
  get 'contact' => 'pages#Contact'
  get 'press' => 'pages#Press'
  get 'builds' => 'pages#Builds'

  get 'pages/Home'

  get 'pages/Contact'

  get 'pages/Administration'

  get 'pages/Press'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :mainImg, :styles => { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :mainImg, :content_type => /\Aimage\/.*\Z/
	
  has_attached_file :img1, :styles => { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :img1, :content_type => /\Aimage\/.*\Z/
	
  has_attached_file :img2, :styles =>  { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :img1, :content_type => /\Aimage\/.*\Z/
	
  has_attached_file :img3, :styles =>  { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :img1, :content_type => /\Aimage\/.*\Z/

  has_attached_file :img4, :styles => { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :img1, :content_type => /\Aimage\/.*\Z/
	
  has_attached_file :img5, :styles => { :medium => "600x450#", :thumb => "400x300#" }, processors: [:thumbnail, :paperclip_optimizer], :default_url => "missingShort.jpg"
  validates_attachment_content_type :img1, :content_type => /\Aimage\/.*\Z/
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Array.new
    Rails.configuration.x.displayOptions.gameCategories.each do |cat|
      @projects.push(Project.where("category = ?", cat).order("pubDate DESC"))
    end

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new

    authorize! :create, @project
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @categories = Rails.configuration.x.displayOptions.gameCategories
    authorize! :update, @project
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    if @project.inProgress
      @project.pubDate =  Date.new(2030,2,3)
    end

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update



    respond_to do |format|
      if @project.update(project_params)
        if @project.inProgress
          @project.pubDate =  Date.new(2030,2,3)
        end
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    authorize! :create, @project
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :summary, :category, :client, :playLink, :videoLink, :mainImg, :img1, :img2, :img3, :img4, :img5, :pubDate, :location, :collaborators, :inProgress, :show, :auxTitle, :aux, :img0Class, :img1Class, :img2Class, :img3Class, :img4Class, :img5Class)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <hr>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>

        <div class="form-group">
          <%= f.label :category %> Please add in Plural form)<br>

                <%= f.select :category,Rails.configuration.x.displayOptions.gameCategories,{}, class: "form-control" %>
              </div>

        </div>
      </div>

    <hr>

        <div class="row">
          <div class="col-md-1"></div>
          <div class="col-md-5">

                <div class="form-group">
                  <label>Client (separate by comma)</label>
                  <%= f.text_area :client, class: "form-control"  %>
                </div>
            <div class="form-group">
              <label>Publish Date (If in development this will not show)</label>
              <%= f.date_select :pubDate, options = {:start_year => 2000, :end_year => 2030, :discard_day => true}, class: "form-control"  %>
            </div>
            <div class="form-group">
              <label>Location</label>
              <%= f.text_field :location, class: "form-control"  %>
            </div>
            <div class="form-group">
              <label>Collaborators (separate by comma)</label>
              <%= f.text_area :collaborators, class: "form-control"  %>
            </div>
                <div class="form-group">
                  <label>Website (external website or link to hosted playable build)</label>
                  <%= f.text_field :playLink, class: "form-control"  %>
                </div>
                <div class="form-group">
                  <label>Link to Youtube video</label>
                  <p>This is not implemented in the view yet. Please fill this out so that your entry will be future compatible.</p>
                  <%= f.text_field :videoLink, class: "form-control"  %>
                </div>
        </div>
        <div class="col-md-5">
          <div class="form-group">
            <label>Custom Field</label>
            <p>WARNING: This is not an HTML safe field. Custom HTML can be added for a completely custom field. Use Caution!</p>
            <label>Field Title</label><%= f.text_field :auxTitle, class: "form-control"  %>
            <label>Field Data</label><%= f.text_field :aux, class: "form-control"  %>
          </div>
        </div>


  </div>

<hr>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-10">


        <div class="form-group">
          <%= f.label :summary %><br>
          <%= f.cktext_area :summary, :value => @project.summary, :id => 'sometext' %>
        </div>

    </div>
  </div>
    <hr>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.label "Main Image (Required)" %>
          <%= f.file_field :mainImg , class: "form-control" %>
         
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.mainImg? %>
        <%= image_tag @project.mainImg.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <%= f.label "Gallery Images" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.file_field :img1 , class: "form-control" %>
          	  
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.img1? %>
        <%= image_tag @project.img1.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.file_field :img2 , class: "form-control" %>
          
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.img2? %>
        <%= image_tag @project.img2.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.file_field :img3 , class: "form-control" %>
          
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.img3? %>
        <%= image_tag @project.img3.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.file_field :img4 , class: "form-control" %>
          
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.img4? %>
        <%= image_tag @project.img4.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="form-group">
          <%= f.file_field :img5 , class: "form-control" %>

          
        </div>
      </div>
      <div class="col-md-6">
        <% if @project.img5? %>
        <%= image_tag @project.img5.url(:thumb), class: "well"  %>
        <% else %>
            <label>NO IMAGE UPLOADED</label>
        <% end %>
      </div>
    </div>



    <hr>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <label>In Development?</label>
        <%= f.check_box :inProgress %>
      </div>
    </div>

    <hr>
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <p>Are you ready for this to be displayed? Leave unpublished to come back later and finish.</p>
        <label>Published</label>
        <%= f.check_box :show %>
      </div>
      <div class="col-md-5">
    <div class="form-group">
      <%= f.submit "Submit", class: 'btn' %>
    </div>
          </div>
        </div>
    <hr>
<% end %>

app/views/projects/edit.html.erb
<div class="row transparent full" style="overflow: hidden; padding-left: 0px; ">
  <div class="row greyTransparent diagonal" style=" overflow: hidden; padding-left: 0px;">
    <div class="col-lg-5 col-md-7 col-sm-12" style="padding: 0">
     	<img  class="img-responsive" src="<%= asset_path('newProject.jpg') %>"></img>
    </div>
  </div>
  
  <div class="row transparent"  style="border-top: solid 1px #000; ">
    <h1 style="margin: .1rem .5rem 0rem" >EDIT PROJECT</h1>
  </div>
  <div class="row transparent"  >
    <h3 style="margin: 0rem .5rem .5rem" >Project creation and editing manager</h3>
  </div>
  
  
  <div class="row light" style="padding-top: 30px; padding-bottom: 30px; border-top: solid 1px #000;  min-height: 100vh;" >
  	 
  

        <div class="col-md-1"></div>
        <div class="col-md-5">
           <%= render 'form' %>


        </div>
        
        </div>

  
  
  
  
  
  </div>
</div>

app/views/projects/index.html.erb
<div class="row transparent full" style="overflow: hidden; padding-left: 20px; padding-right: 20px">
   <% @projects.each do |projectSet| %>
      <% if !projectSet.empty? %>

        <div class="row transparent" style="padding-left: 20px; padding-right: 20px; margin-bottom: 1%;  margin-top: 20px;background-color: RGBA(150,150,150,0.1);">
            <h1 class="blackBack"><%= projectSet.first.category %></h1>
        

      <div class="row ">

        <% projectSet.each do |project| %>
            <% if project.show or can? :update, project %>

            <a class="projectLinks" href="<%= project_path(project) %>">
                <div class="gridParent" >
				<% if !project.show %>
				  <div class="gridContent redDiagonal">
			  	<% else %>
			  		<div class="gridContent diagonal">
                  <% end %>
					
					
						 <%= image_tag project.mainImg.url(:thumb), alt: "", lazy: true ,:class => "img-responsive" %>
						 <h4 style="margin: .1rem .5rem .1rem"><%= project.title %></h4>
						 <% if project.inProgress %>
							<p style="margin: .1rem .5rem .5rem;  line-height: 1;">In Development</p>
						<% else %>
							<p style="margin: .1rem .5rem .5rem;  line-height: 1;"><%= project.pubDate.strftime("%B %d %Y")%></p>
                 		 <% end %>
					</div>
                 
				
                </div>
            </a>

        <% end %>

      <% end %>
      </div>
	  </div>
          <% end %>
    <% end %>

</div>
<script>
    $("img").lazyload({
        effect : "fadeIn"
		
    });
	
		$("img").load(function(){
	  $(".CenterIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", (((parW - childW) / 2) / parW) * 100 + "%" );
		});
	});
	
	$( window ).resize(function() {
		$(".CenterIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", (((parW - childW) / 2) / parW) * 100 + "%" );
		});
	});
	
	$("img").load(function(){
	  $(".LeftIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", "0px");
		});
	});
	
	$( window ).resize(function() {
		$(".LeftIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", "0px" );
		});
	});
	
	$("img").load(function(){
	  $(".RightIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left",  ((parW - childW) / parW) * 100 + "%");
		});
	});
	
	$( window ).resize(function() {
		$(".RightIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left",  ((parW - childW) / parW) * 100 + "%" );
		});
	});
	
		
</script>

app/views/projects/new.html.erb
<div class="row transparent full" style="overflow: hidden; padding-left: 0px; ">
  <div class="centerPage">

    <div style="overflow: hidden; height:25vh; width: 832px;">
      <img  src="<%= asset_path ('newProject.jpg') %>" style="width: 832px; "></img>
    </div>
    <h1 class="center" style="margin-top: -20vh; position: relative;">NEW PROJECT</h1>


<%= render 'form' %>



      </div>
    </div>

app/views/projects/show.html.erb
<div class="row full" style="overflow: hidden; padding-left: 0px; ">
  <div class="row " style=" background-color: #000; overflow: hidden; padding-left: 0px">
    <div class="col-md-12" style="padding: 0">
      <div class="owl-carousel ">
		  
        <div class="item half loading" style="overflow: hidden; "><img  class="owl-lazy" data-src="<%= @project.mainImg.url(:medium) %>"  alt=""></div>

        <% if @project.img1? %>
            <div class="item  half loading" style="overflow: hidden;"><img class="owl-lazy"  data-src="<%= @project.img1.url(:medium) %>"  alt=""></div>
        <% end %>
        <% if @project.img2? %>
            <div class="item  half loading" style="overflow: hidden; "><img class="owl-lazy"  data-src="<%= @project.img2.url(:medium) %>" alt=""></div>
        <% end %>
        <% if @project.img3? %>
            <div class="item half loading" style="overflow: hidden; "><img class="owl-lazy "  data-src="<%= @project.img3.url(:medium) %>" alt=""></div>
        <% end %>
        <% if @project.img4? %>
            <div class="item half loading" style="overflow: hidden; "><img class="owl-lazy "  data-src="<%= @project.img4.url(:medium) %>" alt=""></div>
        <% end %>
        <% if @project.img5? %>
            <div class="item half loading" style="overflow: hidden;  "><img class="owl-lazy "  data-src="<%= @project.img5.url(:medium) %>" alt=""></div>
        <% end %>


      </div>
    </div>
  </div>

<div class="row transparent"  style="border-top: solid 1px #000; ">
    <h1 style="margin: .1rem .5rem 0rem" ><%= @project.title %></h1>
  </div>
  <div class="row transparent"  >
    <h3 style="margin: 0rem .5rem .5rem" ><%= @project.category %></h3>
  </div>


  <div class="row light" style="padding-top: 30px; padding-bottom: 30px; border-top: solid 1px #000;  min-height: 100vh;" >

    <div class="col-lg-2 col-md-3" >
      <h2>Publish Date</h2>
      <% if @project.inProgress %>
            In Development
      <% else %>
          <%= @project.pubDate.strftime("%B")  %>  <%= @project.pubDate.strftime("%Y")  %>
      <% end %>
        <hr>
      <% if !@project.location.blank? %>
          <h2>Location</h2>
          <%= @project.location %>
          <hr>
      <% end %>
      <% if !@project.client.blank? %>
          <h2>Clients</h2>
          <%= @project.client %>
          <hr>
      <% end %>
      <% if !@project.collaborators.blank? %>
          <h2>Collaborators</h2>
          <%= @project.collaborators %>
          <hr>
      <% end %>
      <% if !@project.playLink.blank? %>
          <h2>Website</h2>
            <a href="<%= @project.playLink %>" target="_blank">Link</a>

          <hr>
      <% end %>
      <% if !@project.aux.blank? %>

          <h2><%= @project.auxTitle %></h2>
          <%= @project.aux.html_safe %>
          <hr>
      <% end %>
		
	
      <% if can? :update, @project %><%= link_to 'Edit', edit_project_path(@project) %><%end%> <% if can? :delete, @project %> | <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' } %> <i class="fa fa-exclamation-triangle"></i><%end%>

    </div>


    <div class="col-lg-6 col-md-7 blogContent" >

     <%= @project.summary.html_safe %>
    </div>






    </div>
</div>



<script>
    $(document).ready(function(){
        $('.owl-carousel').owlCarousel({
            responsiveClass:true,
            responsive:{
                0:{
                    items:1
                },
                1000:{
                    items:2
                },
                1300:{
                    items:3
                },
                2000:{
                    items:4
                }
            },
            lazyLoad:true,
            loop:true,
            
            margin:3,
            autoplaySpeed: 2000,
            autoplay:true,
            autoplayTimeout:3500,
            autoplayHoverPause:true
        });
    });
	
	$("img").load(function(){
	  $(".CenterIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", (((parW - childW) / 2) / parW) * 100 + "%" );
		});
	});
	
	$( window ).resize(function() {
		$(".CenterIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", (((parW - childW) / 2) / parW) * 100 + "%" );
		});
	});
	
	$("img").load(function(){
	  $(".LeftIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", "0px");
		});
	});
	
	$( window ).resize(function() {
		$(".LeftIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left", "0px" );
		});
	});
	
	$("img").load(function(){
	  $(".RightIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left",  ((parW - childW) / parW) * 100 + "%");
		});
	});
	
	$( window ).resize(function() {
		$(".RightIMG").each(function(){
			var childImg = $(this);
			var childW = childImg.width();
			var parW = childImg.parent().width();
			childImg.css("margin-left",  ((parW - childW) / parW) * 100 + "%" );
		});
	});


</script>